formas:
 - nombre : "Dependencias"
   campos:
    - nombre: "dependenciaBaseDatos"
      etiqueta: "Dependencia base de datos"
      descripcion: "Ej: mysql"
      tipoCtrl: "textbox"
    - nombre: "versionDependenciaBaseDatos"
      etiqueta: "Version de la dependencia de base de datos"
      descripcion: "Ej: ^2.18.1"
      tipoCtrl: "textbox"
 - nombre : "Orm Config"
   campos:
    - nombre: "tipoBaseDatos"
      etiqueta: "Tipo de base de datos a usar, ej: mysql"
      descripcion: "Ej: mysql"
      tipoCtrl: "textbox"
    - nombre: "host"
      etiqueta: "Hos para establecer conexión, ej: localhost"
      descripcion: "Ej: localhost"
      tipoCtrl: "textbox"
    - nombre: "puerto"
      etiqueta: "Puerta de conexión a la base de datos, ej: 3307"
      descripcion: "Ej: 3307"
      tipoCtrl: "textbox"
    - nombre: "username"
      etiqueta: "Usuario de base de datos"
      descripcion: "Ej: root"
      tipoCtrl: "textbox"
    - nombre: "password"
      etiqueta: "Password del usuario"
      descripcion: "Ej: root"
      tipoCtrl: "textbox"
    - nombre: "baseDatos"
      etiqueta: "Nombre de la base de datos. ej: test"
      descripcion: "Ej: test"
      tipoCtrl: "textbox"

